-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "colorTransitions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isMultiColor" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "primeTowerCost" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "purgeWasteCost" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "selectedSlots" INTEGER[],
ALTER COLUMN "color" DROP NOT NULL,
ALTER COLUMN "color" DROP DEFAULT;
